name: gitleaks
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  gitleaks:
    uses: teemow/github-workflows/.github/workflows/gitleaks.yml@main
    with:
      runs-on: ubuntu-latest
